// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkXefvcz_ZuMfj-EPLkYCjIeFKviJSc9Y',
    appId: '1:366679648636:web:530253bb4ab70b75635cf9',
    messagingSenderId: '366679648636',
    projectId: 'bijak-kipk',
    authDomain: 'bijak-kipk.firebaseapp.com',
    storageBucket: 'bijak-kipk.appspot.com',
    measurementId: 'G-7WKM99HBGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwHq89z_IBPNemNNhZZkiwZxq7gMP-t3E',
    appId: '1:366679648636:android:dedc6581890e961a635cf9',
    messagingSenderId: '366679648636',
    projectId: 'bijak-kipk',
    storageBucket: 'bijak-kipk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPNflb2uim0-HK2KG-hZf-IT22g6Cia4w',
    appId: '1:366679648636:ios:fcbec3706d7a727b635cf9',
    messagingSenderId: '366679648636',
    projectId: 'bijak-kipk',
    storageBucket: 'bijak-kipk.appspot.com',
    androidClientId:
        '366679648636-9bpffooa4u8hf1gitq6orbul135ldhlt.apps.googleusercontent.com',
    iosClientId:
        '366679648636-v8su8ktgqfs9haoad9ke4s34i44giksd.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperSnippet',
  );
}
